name: video-analyzer
version: 2.0.0
description: 智能分析 Bilibili/YouTube/本地视频，生成转写、评估和总结。支持关键帧截图自动嵌入。
author: user
type: utility

triggers:
  - "分析视频"
  - "转写视频"
  - "总结视频内容"
  - "评估这个视频"
  - "视频内容分析"
  - "提取视频文字"

capabilities:
  - video_transcription
  - content_evaluation
  - bilibili_search
  - multi_platform_support

parameters:
  url:
    type: string
    required: true
    description: 视频链接或本地视频文件路径
  
  whisper_model:
    type: choice
    default: large-v2
    options: [tiny, base, small, medium, large-v2, large-v3, turbo, distil-large-v2, distil-large-v3, distil-large-v3.5]
    description: Whisper模型名称（仅多语言模型，已移除所有单语言.en模型）
  
  analysis_types:
    type: multi_choice
    default: [evaluation, summary]
    options: [evaluation, summary, format]
    description: 分析类型列表
  
  output_dir:
    type: string
    default: "./video-analysis"
    description: 输出目录路径
  
  save_transcript:
    type: boolean
    default: true
    description: 是否保存原始转写文件
  
  summary_style:
    type: choice
    default: deep_longform
    options: [brief_points, deep_longform, social_media, study_notes]
    description: Summary style (简洁要点, 深度长文, 社媒文案, 学习笔记)
  
  enable_screenshots:
    type: boolean
    default: true
    description: 启用关键帧截图提取（默认启用，自动在总结中插入关键节点截图）

examples:
  - "分析这个视频 https://www.bilibili.com/video/BV1xx411c7mD"
  - "转写 YouTube 视频 https://youtu.be/xxx，使用 small 模型"
  - "分析 B站视频 ./my-video.mp4，只做评估和总结"
  - "搜索 B站'Python教程'，分析前3个视频"

output:
  format: structured
  schema:
    success: boolean
    video_title: string
    duration_seconds: number
    transcript_length: number
    output_files:
      transcript: string
      evaluation: string
      summary: string
    summary: string

dependencies:
  python:
    yt-dlp: ">=2024.0.0"
    faster-whisper: ">=1.0.0"
    modelscope: ">=1.0.0"
    opencc-python-reimplemented: ""
    openai: ">=1.0.0"
    anthropic: ">=0.18.0"
    bilibili-api-python: ""
    tenacity: ">=8.0.0"
  system:
    ffmpeg: ""
    ffprobe: ""
