---
name: add-top-openrouter-models
display_name: "Add Top OpenRouter Models"
description: Sync top OpenRouter models used by OpenClaw into this installation's config. Fetches the OpenClaw app leaderboard, verifies model IDs against the API catalog, and adds missing models with correct specs and aliases.
version: 1.0.0
triggers:
  - sync openrouter models
  - add openrouter models
  - update openrouter models
  - check openrouter models
  - add missing models
  - openrouter model sync
